### ISSUE TITLE
Error while running interact.js

### ISSUE THREAD

**Issue by ugmqu** [alchemyplatform/hello-world-tutorial#1]
Hello, i got the following Error message, while runnign your interact,js:

C:\Users\username\Documents\Hardhat_Alchemie\node_modules\@ethersproject\logger\src.ts\index.ts:261
        const error: any = new Error(message);
                           ^
Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.6.0)
    at Logger.makeError (C:\Users\username\Documents\Hardhat_Alchemie\node_modules\@ethersproject\logger\src.ts\index.ts:261:28)
    at Logger.throwError (C:\Users\username\Documents\Hardhat_Alchemie\node_modules\@ethersproject\logger\src.ts\index.ts:273:20)
    at Logger.throwArgumentError (C:\Users\username\Documents\Hardhat_Alchemie\node_modules\@ethersproject\logger\src.ts\index.ts:277:21)
    at Contract.BaseContract (C:\Users\username\Documents\Hardhat_Alchemie\node_modules\@ethersproject\contracts\src.ts\index.ts:714:20)
    at new Contract (C:\Users\username\Documents\Hardhat_Alchemie\node_modules\@ethersproject\contracts\lib\index.js:1054:42)
    at Object.<anonymous> (C:\Users\username\Documents\Hardhat_Alchemie\scripts\interact.js:14:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
PS C:\Users\username\Documents\Hardhat_Alchemie>

**Comment by ugmqu** [comment]
I named the variable CONTRACT_ADDRESS slightly differend inside my .env 
Thats what causes the error.
